return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",

  config = function () 
    local configs = require("nvim-treesitter.configs")

    configs.setup({
      auto_install = true,
      ensure_installed = {
        -- "angular",
        "astro",
        "bash",
        -- "cmake",
        "cpp",
        -- "c_sharp",
        "css",
        -- "csv",
        -- "dart",
        "diff",
        -- "doxygen",
        -- "dtd",
        "editorconfig",
        -- "gitattributes",
        "gitcommit",
        "git_config",
        "gitignore",
        "git_rebase",
        "glsl",
        "go",
        -- "graphql",
        "html",
        -- "idl",
        -- "java",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "lua",
        "python",
        "rust",
        "scss",
        "ssh_config",
        -- "svelte",
        -- "toml",
        "typescript",
        "vim",
        "vimdoc",
        -- "vue",
        -- "xml",
        "yaml",
      },
      ignore_install = { "query" },
      sync_install = false,
      highlight = { enable = not vim.g.vscode },
      indent = { enable = true },  
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<cr>",
          node_incremental = "<m-right>",
          scope_incremental = "<m-up>",
          node_decremental = "<m-left>",
        },
      },
    })
  end
}
